//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int ID { get; set; }
        public int JournalID { get; set; }
        public System.DateTime Date { get; set; }
        public int CountOfHours { get; set; }
        public string Theme { get; set; }
        public string Homework { get; set; }
    
        public virtual Journal Journal { get; set; }
    }
}
